homework 1 has done
ok-technopolis-autumn-2022/Vladislav_Yartsev pull request #1
Opened 2022-09-27 11:53 UTC by StombieIT

Свёрстан HTML макет по методологии BEM.

2022-09-29 06:59 UTC, fromanywhere requested changes
Вообще довольно близко к тому, что ожидалось. Чистенько, структурировано, неплохо по семантике.

Вектор улучшения — уделить больше внимания управляющим элементам

2022-09-29 06:59 UTC, fromanywhere commented on index.html
> +                    <svg class="todos-widget__header-show-btn"></svg>
svg нарисует графику, но не добавит функциональность. Здесь должно быть что-то, что сможет выбрать / снять выделение со всех элементов списка (понятно, что сама логика будет сделана на js, но нужно же будет её как-то запускать)

2022-09-29 06:59 UTC, fromanywhere commented on index.html
> +                    <input tabindex="1" type="text" placeholder="What needs to be done?">
Нужны ли tabindex? Как контролировать растущее количество элементов в приложении, если tabindex выставлен руками?

2022-09-29 06:59 UTC, fromanywhere commented on index.html
> +                            <input name="todo1" type="checkbox" tabindex="2">
Какая функциональность здесь ожидается?

2022-09-29 06:59 UTC, fromanywhere commented on index.html
> +                        </div>
А как удалять элемент?

2022-09-29 06:59 UTC, fromanywhere commented on index.html
> +                            <label for="todo1">HTML</label>
В чем идея for?

2022-09-29 06:59 UTC, fromanywhere commented on index.html
> +                        <button tabindex="3" class="btn btn-active" href="#">
Это кнопка или ссылка? Или, может, вообще что-то другое?

2022-09-29 07:23 UTC, StombieIT commented on index.html
> +                    <svg class="todos-widget__header-show-btn"></svg>
Я хотел повесить обработчик события на svg. Ладно, тогда попробую реализовать через функциональные теги.

2022-09-29 11:50 UTC, StombieIT commented on index.html
> +                        </div>
У меня была идея на каждый li повесить слушатели событий mouseover и mouseout, и в первом случае добавлять кнопку, а во втором удалять. Это можно сделать и через стили, но тогда каждая кнопка будет в HTML дереве, и её нужно скрыть стилями. Мне первый вариант показался более привлекательным. В последнем li есть кнопка.

2022-09-29 12:06 UTC, fromanywhere commented on index.html
> +                        </div>
Что будет, если пользователь будет смотреть Ваше приложение с телефона?

2022-10-04 10:25 UTC, StombieIT commented
Добавлены accessability атрибуты.

2022-10-05 10:31 UTC, fromanywhere requested changes

2022-10-05 10:31 UTC, fromanywhere commented on index.html
> +                    <div class="todos-widget__footer-section" role="buttons container">
role=radiogroup + aria-label

2022-10-08 09:55 UTC, StombieIT commented
Замечания исправлены

2022-10-08 11:19 UTC, fromanywhere requested changes

2022-10-08 11:19 UTC, fromanywhere commented on index.html
> +                        aria-label="Select all todos"
на кнопках с иконками без текста лучше использовать title

2022-10-08 11:19 UTC, fromanywhere commented on index.html
> +                    <div class="todos-widget__footer-section" role="radiogroup">
по спецификации у radiogroup должен быть «заголовок». Я предлагаю через aria-label

2022-10-08 12:01 UTC, StombieIT commented on index.html
> +                    <div class="todos-widget__footer-section" role="radiogroup">
Исправлено

2022-10-08 12:13 UTC, StombieIT commented on index.html
> +                        aria-label="Select all todos"
Исправлено

2022-10-08 21:05 UTC, StombieIT commented
Замечания исправлены

2022-10-10 08:49 UTC, fromanywhere approved these changes

2022-10-10 09:30 UTC, merged