Homework2 - Yartsev Vladislav
ok-technopolis-autumn-2022/Vladislav_Yartsev pull request #2
Opened 2022-10-15 19:48 UTC by StombieIT

Добавлены стили

2022-10-17 07:42 UTC, fromanywhere requested changes
Нужно быть снайпером, чтобы попасть в кнопку такого размера (увеличиваем активную область)
<img width="364" alt="image" src="https://user-images.githubusercontent.com/1042969/196116239-a30e1107-daec-49ad-9c89-2d9a2bddb66a.png">

Всё, что правее плейсхолдера, некликабельное. Увеличиваем кликабельную площадь поля ввода до правой границы и занимаем всю высоту строки
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1042969/196116455-c2e5ca21-6c7e-4353-8acd-351ca6df128f.png">

Тут всё прилипло
<img width="54" alt="image" src="https://user-images.githubusercontent.com/1042969/196116789-136972d2-cbdf-4a6f-b6a7-bbc098c4f74c.png">

Здесь тоже пиксельхантинг
<img width="320" alt="image" src="https://user-images.githubusercontent.com/1042969/196117131-ed667e4a-271c-45b3-84d3-7f56bfb07c0a.png">

Какая-то дырка в конце скролла
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1042969/196117339-d57ecc3b-e5e1-49c2-b5ef-70ce505b7b3f.png">

Макет должен уметь проходиться с клавиатуры табом насквозь. Любой интерактивный элемент на фокус должен иметь какую-то подсветку (в макете нет, простор для фантазии). Правильно сверстанный контрол нажимается пробелом из коробки

В целом довольно неплохо, но нужно больше думать о пользователе

2022-10-17 07:42 UTC, fromanywhere commented on common.blocks/todos-widget/__footer-section-switcher/todos-widget__footer-section-switcher.css
> +    outline: 2px solid var(--shading-color);
outline нехорошо — его лучше оставить под подсветку фокуса. Здесь лучше border, но нужно подумать, как сделать, чтобы футер не дергался при переключении фильтров

2022-10-17 07:42 UTC, fromanywhere commented on common.blocks/todos-widget/__footer/todos-widget__footer.css
> +    align-content: flex-end;
это вроде лишнее

2022-10-17 07:42 UTC, fromanywhere commented on common.blocks/todos-widget/__header/todos-widget__header.css
> +    align-content: flex-start;
это вроде тоже лишнее

2022-10-17 07:42 UTC, fromanywhere commented on index.css
> +    outline: none;
Здесь умерла вся клавиатурная доступность — пользователь при табуляции не понимает, где он находится

2022-10-17 07:42 UTC, fromanywhere commented on index.html
> +                        <svg width="24" height="12" viewBox="0 0 24 12" fill="none" xmlns="http://www.w3.org/2000/svg">
Почему Вы решили тут инлайнить svg?

2022-10-17 08:03 UTC, StombieIT commented on common.blocks/todos-widget/__footer/todos-widget__footer.css
> +    align-content: flex-end;
без этого свойства средний блок (со списком todo'шек) всегда по максимуму растягивается, его размер не получается ограничить

2022-10-17 08:03 UTC, StombieIT commented on common.blocks/todos-widget/__header/todos-widget__header.css
> +    align-content: flex-start;
аналогично

2022-10-17 08:31 UTC, fromanywhere commented on common.blocks/todos-widget/__footer/todos-widget__footer.css
> +    align-content: flex-end;
На самом деле это не решает проблему.
Обратите внимание — если элементов списка будет очень много — скажем, несколько десятков, — у Вас появится второй скролл на уровне body (вариант делать overflow:hidden на body не принимается).
Это довольно примечательный баг. Лучше всего его пытаться раздебажить, последовательно скрывая содержимое элемента списка, чтобы понять, какой из элементов дает такой эффект

2022-10-22 20:11 UTC, StombieIT commented on common.blocks/todos-widget/__footer-section-switcher/todos-widget__footer-section-switcher.css
> +    outline: 2px solid var(--shading-color);
Исправлено: https://github.com/ok-technopolis-autumn-2022/Vladislav_Yartsev/pull/2/commits/4f01cc7b34f927999787bb6f5a8bd874c4cdaafc + https://github.com/ok-technopolis-autumn-2022/Vladislav_Yartsev/pull/2/commits/e497c0806e8fa5c0451c25ac20dee60bf6b939b7

2022-10-22 20:43 UTC, StombieIT commented on index.html
> +                        <svg width="24" height="12" viewBox="0 0 24 12" fill="none" xmlns="http://www.w3.org/2000/svg">
Согласен, решение не очень. Исправлено: https://github.com/ok-technopolis-autumn-2022/Vladislav_Yartsev/pull/2/commits/bf708956efabe430e1257ae664cdc22f4ad39e97

2022-10-23 08:11 UTC, StombieIT commented on index.css
> +    outline: none;
Исправлено: https://github.com/ok-technopolis-autumn-2022/Vladislav_Yartsev/pull/2/commits/fd8646d465a88a09a4f1b2c6985934269b0d8f80

2022-10-24 07:28 UTC, fromanywhere requested changes
<img width="143" alt="Снимок экрана 2022-10-24 в 10 27 47" src="https://user-images.githubusercontent.com/1042969/197470938-8967a7ed-d4f9-4e29-8941-8f87fe7b13ab.png">
Левый край поля ввода и текст элементов списка не выровнены по левому краю

2022-10-24 07:28 UTC, fromanywhere commented on common.blocks/todos-widget/__footer/todos-widget__footer.css
> +    align-content: flex-end;
<img width="1903" alt="Снимок экрана 2022-10-24 в 10 23 13" src="https://user-images.githubusercontent.com/1042969/197470311-a3511f6f-6a3d-4f7c-9f98-06d27c268cf9.png">
Всё еще остается. Обратите внимание на двойной скролл при большом количестве элементов

2022-10-24 07:28 UTC, fromanywhere commented on common.blocks/todos/__todo/todos__todo.css
> +    position: absolute;
Из-за того что оно написано так, невозможно удалить элемент с клавиатуры

2022-10-24 07:31 UTC, fromanywhere commented
Еще 
<img width="659" alt="image" src="https://user-images.githubusercontent.com/1042969/197471428-f1e438a1-9ce6-4f16-b6fa-79754f6aab87.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1042969/197471505-6967d7dd-5e3c-4664-aad5-5a27f96ba43c.png">

2022-10-24 09:40 UTC, StombieIT commented
Исправлен баг со скроллом: https://github.com/ok-technopolis-autumn-2022/Vladislav_Yartsev/pull/2/commits/44bbccfe7f1c0d419da219bd9066f2dcd5250500

2022-10-24 16:15 UTC, StombieIT commented on common.blocks/todos/__todo/todos__todo.css
> +    position: absolute;
Исправлено: https://github.com/ok-technopolis-autumn-2022/Vladislav_Yartsev/pull/2/commits/86e24df1fd6c0317e6e24cda6de7e9aef09362c0

2022-10-24 17:27 UTC, StombieIT commented
Замечания исправлены

2022-10-25 09:52 UTC, fromanywhere commented
Почему 300 я так и не понял, но спишем на авторское решение 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1042969/197742612-62e6e82e-488f-4a4e-81a3-bf25262afa16.png">

2022-10-25 09:52 UTC, fromanywhere approved these changes

2022-10-26 15:51 UTC, merged