Homework4 - Yartsev Vladislav
ok-technopolis-autumn-2022/Vladislav_Yartsev pull request #4
Opened 2022-11-19 16:30 UTC by StombieIT

2022-11-21 08:27 UTC, fromanywhere requested changes

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos-widget/__footer-section-switcher/todos-widget__footer-section-switcher.js
> +const todosWidgetFooterSectionSwitcherInputs = [...document.querySelectorAll(".todos-widget__footer-section-switcher")]
А почему нельзя просто document.querySelectorAll('.todos-widget__footer-section-switcher input')?

Кстати, есть правило хорошего тона на все узлы, к которым ходят через js, вешать js-специфичные селекторы. Чтобы потом можно было дешево менять стили/разметку, и не лезть при этом в js-код. Например, такие селекторы можно именовать с префиксом js — н-р .js-footer-switcher

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos-widget/__footer-section-switcher/todos-widget__footer-section-switcher.js
> +todosWidgetFooterSectionSwitcherInputs.forEach(input => input.addEventListener("change", evt => {
Вот это вот в цикле — это избыточно. Попробуйте оформить через делегирование (всплытие)

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos-widget/__header/todos-widget__header.js
> +todosWidgetHeader.addEventListener("keydown", evt => {
так скучно. Давайте сделаем сабмит формы

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos-widget/__header/todos-widget__header.js
> +let key = 1
я бы вынес генерацию айдишки в отдельную утилиту. Во-первых такое бывает нужно разным компонентам, во-вторых, можно будет проще изменить реализацию, если это потребуется

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos/__todo-btn/_action/todos__todo-btn_action_remove.js
> +    button.classList.add("btn")
classList.add умеет classList.add("btn", "todos__todo-btn_action_remove"), а можно и просто className

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos/__todo-btn/_action/todos__todo-btn_action_remove.js
> +    button.addEventListener("click", evt => onRemove())
есть ли смысл делать вызов функции внутри обработчика? Можно просто передать ссылку button.addEventListener("click", onRemove)

2022-11-21 08:27 UTC, fromanywhere commented on store.js
> +        return todosType === Store.TodosType.ALL ||
Интересно, а можно это оформить как-то типа Object.values(Store.TodosType).includes(todosType)

2022-11-21 08:27 UTC, fromanywhere commented on common.blocks/todos-widget/todos-widget.js
> +            onRemove: () => {
Тут тоже нужно подумать над делегацией. Фактически тут одна зависимость — todo.key. Если бы её можно было получать из самого элемента (есть несколько способов это делать), то можно было бы не навешивать обработчики на каждый элемент (и не пересоздавать обработчики на каждый чих)

2022-11-21 08:28 UTC, fromanywhere commented
Я бы кстати еще какой-нибудь eslint накрутил поверх для профилактики

2022-11-23 08:15 UTC, StombieIT commented on common.blocks/todos-widget/__header/todos-widget__header.js
> +todosWidgetHeader.addEventListener("keydown", evt => {
хорошо)

2022-11-23 10:22 UTC, StombieIT commented
Замечания исправлены

2022-11-23 10:31 UTC, fromanywhere approved these changes
Следует признать, что решение достаточно изящное, я ожидал больше спагетти в этой работе

Теперь отчетливо видно, что .todos__todo-checkbox input[type=checkbox] + label { max-width } — самое слабое звено на текущий момент

После сабмита не очищается поле ввода — оставляю Вам на доработку

Зачтено

2022-11-23 10:35 UTC, StombieIT commented
Поправил кнопки удаления и выделения всего

2022-11-26 11:42 UTC, merged